            - name: Soda Library Action
  # You may pin to the exact commit or the version.
  # uses: sodadata/soda-github-action@9c5c12a9c29b3a48d3069b8b62a84b0c2090f9fc
  uses: sodadata/soda-github-action@v1.0.2
  with:
    # Version of the Soda Library on which to run the scan
    soda_library_version: 
    # Data Source name
    data_source: 
    # Configuration file
    configuration: 
    # Checks file(s)
    checks: 
          
